spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_db
    username: demo_user
    password: demo_password
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 8080
